/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PM;

import java.awt.HeadlessException;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class frmDriver extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmDriver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDid = new javax.swing.JTextField();
        txtDname = new javax.swing.JTextField();
        txtDphn = new javax.swing.JTextField();
        txtDemail = new javax.swing.JTextField();
        txtDage = new javax.swing.JTextField();
        txtDaddress = new javax.swing.JTextField();
        txtDdate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmdDnew = new javax.swing.JButton();
        cmdDsave = new javax.swing.JButton();
        cmdDsearch = new javax.swing.JButton();
        cmdDdelete = new javax.swing.JButton();
        cmdDcancle = new javax.swing.JButton();
        cmdDprint = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cmdDclear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDlic = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmdDel = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDid.setEditable(false);
        txtDid.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDid.setToolTipText("Driver Id");

        txtDname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDname.setToolTipText("Driver Name");
        txtDname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDnameKeyPressed(evt);
            }
        });

        txtDphn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDphn.setToolTipText("Eenter Contact Number");
        txtDphn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDphnFocusLost(evt);
            }
        });
        txtDphn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDphnKeyPressed(evt);
            }
        });

        txtDemail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDemail.setToolTipText("Email Id ");
        txtDemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDemailFocusLost(evt);
            }
        });

        txtDage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDage.setToolTipText("Age");
        txtDage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDageActionPerformed(evt);
            }
        });
        txtDage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDageFocusLost(evt);
            }
        });
        txtDage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDageKeyPressed(evt);
            }
        });

        txtDaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDaddress.setToolTipText("Address");

        txtDdate.setEditable(false);
        txtDdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDdate.setToolTipText("System Date ");

        cmdDnew.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmdDnew.setText("New");
        cmdDnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDnewActionPerformed(evt);
            }
        });

        cmdDsave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmdDsave.setText("Save");
        cmdDsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDsaveActionPerformed(evt);
            }
        });

        cmdDsearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmdDsearch.setText("Search");
        cmdDsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDsearchActionPerformed(evt);
            }
        });

        cmdDdelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmdDdelete.setText("Update");
        cmdDdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDdeleteActionPerformed(evt);
            }
        });

        cmdDcancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/th (23).jpg"))); // NOI18N
        cmdDcancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDcancleActionPerformed(evt);
            }
        });

        cmdDprint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmdDprint.setText("Print");
        cmdDprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDprintActionPerformed(evt);
            }
        });

        cmdDclear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmdDclear.setText("Clear");
        cmdDclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDclearActionPerformed(evt);
            }
        });

        txtDlic.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDlic.setToolTipText("Driver Licens Number");
        txtDlic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDlicFocusLost(evt);
            }
        });
        txtDlic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDlicKeyPressed(evt);
            }
        });

        cmdDel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cmdDel.setText("Delete");
        cmdDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDelActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/driver-Registration-1.jpg"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/th (43).jpg"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/th15.jpg"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/ph2.jpg"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/images (2).png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/download (4).png"))); // NOI18N
        jLabel24.setToolTipText("Age");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/download (2).png"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/download (3).png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PM/download (5).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDemail, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(txtDphn))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDlic, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDid, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDname, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jLabel24)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel3))
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14))
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel16)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtDdate, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDage, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmdDnew)
                        .addGap(18, 18, 18)
                        .addComponent(cmdDsave)
                        .addGap(18, 18, 18)
                        .addComponent(cmdDsearch)
                        .addGap(18, 18, 18)
                        .addComponent(cmdDdelete)
                        .addGap(18, 18, 18)
                        .addComponent(cmdDclear)
                        .addGap(18, 18, 18)
                        .addComponent(cmdDel)
                        .addGap(18, 18, 18)
                        .addComponent(cmdDprint)))
                .addGap(146, 146, 146))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdDcancle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdDcancle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)))))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel20)
                        .addComponent(jLabel24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel21))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel25))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDphn, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addComponent(jLabel16))
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDlic, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)))
                .addGap(18, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdDnew)
                    .addComponent(cmdDsave)
                    .addComponent(cmdDsearch)
                    .addComponent(cmdDdelete)
                    .addComponent(cmdDclear)
                    .addComponent(cmdDel)
                    .addComponent(cmdDprint)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(193, 193, 193))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel5.setText("PACKERS AND MOVERS MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(536, 536, 536))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDageActionPerformed

    private void txtDageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDageFocusLost
        // TODO add your handling code here:
        if(Integer.parseInt(txtDage.getText())<18){
            JOptionPane.showMessageDialog(null,"Invalid Age","Driver Entry",JOptionPane.INFORMATION_MESSAGE);
            txtDage.setText("");
            txtDage.grabFocus();
        }
    }//GEN-LAST:event_txtDageFocusLost

    private void cmdDnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDnewActionPerformed
        // TODO add your handling code here:
        Connection cn;
        Statement st;
        ResultSet rs;
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            cn=DriverManager.getConnection("jdbc:odbc:DATABASE");
            st=cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs=st.executeQuery("select * from Driver" );
            while(rs.next()){
                if(rs.isLast()==true){
                    int tno=Integer.parseInt(rs.getString(1));
                    tno=tno+1;
                    String pno=Integer.toString(tno);
                    txtDid.setText(pno);

                }
            }
        }
        catch(ClassNotFoundException | SQLException | NumberFormatException e )
        {

        }
    }//GEN-LAST:event_cmdDnewActionPerformed

    private void cmdDsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDsaveActionPerformed
        // TODO add your handling code here:
        if(txtDaddress.getText().equals("")||txtDage.getText().equals("")||txtDdate.getText().equals("")||txtDid.getText().equals("")||txtDlic.getText().equals("")||txtDname.getText().equals("")||txtDphn.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Plz...Fill the Information !!!");
        }
        else
        {
        Connection con;
        PreparedStatement pst;

        Calendar cal = Calendar.getInstance();
        cal.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        txtDdate.setText(sdf.format(cal.getTime()));
        if(txtDemail.getText()==null)
        {
            txtDemail.setText("-");
        }

        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:odbc:DATABASE");

            pst=con.prepareStatement("Insert into Driver(ID,Dname,Dphn,Demail,Daddress,Dage,Dlic,Ddate)values(?,?,?,?,?,?,?,?)");
            pst.setString(1, txtDid.getText());
            pst.setString(2, txtDname.getText());
            pst.setString(3, txtDphn.getText());
            pst.setString(4,txtDemail.getText());
            pst.setString(5, txtDaddress.getText());
            pst.setString(6, txtDage.getText());
            pst.setString(7, txtDlic.getText());
            pst.setString(8,txtDdate.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "New Data  Inserted Successfully");
        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,"Data Not Inserted Plz try again ");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmEnquiry.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtDid.setText("");
        txtDname.setText("");
        txtDphn.setText("");
        txtDemail.setText("");
        txtDaddress.setText("");
        txtDage.setText("");
        txtDlic.setText("");
        txtDdate.setText("");
        }

    }//GEN-LAST:event_cmdDsaveActionPerformed

    private void cmdDsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDsearchActionPerformed
        // TODO add your handling code here:
        String N=JOptionPane.showInputDialog("Enter Driver Id");
        Connection cn;
        Statement st;
        ResultSet rs;

        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            cn=DriverManager.getConnection("jdbc:odbc:DATABASE");
            st=cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs=st.executeQuery("select * from Driver where ID="+N);
            while(rs.next()){
                System.out.println(N);
                txtDid.setText(N);
                txtDname.setText(rs.getString(2));
                txtDphn.setText(rs.getString(3));
                txtDemail.setText(rs.getString(4));
                txtDaddress.setText(rs.getString(5));
                txtDage.setText(rs.getString(6));
                txtDlic.setText(rs.getString(7));
                txtDdate.setText(rs.getString(8));

            }
        }
        catch(    ClassNotFoundException | SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Plz Try Again");
        }
    }//GEN-LAST:event_cmdDsearchActionPerformed

    private void cmdDcancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDcancleActionPerformed
        // TODO add your handling code here:
        frmMain f3 = new frmMain();
        f3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cmdDcancleActionPerformed

    private void cmdDprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDprintActionPerformed
        // TODO add your handling code here:
        driverreport1 dr = new driverreport1();
        dr.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_cmdDprintActionPerformed

    private void cmdDclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDclearActionPerformed
        // TODO add your handling code here:
        txtDid.setText("");
        txtDname.setText("");
        txtDphn.setText("");
        txtDemail.setText("");
        txtDaddress.setText("");
        txtDage.setText("");
        txtDlic.setText("");
        txtDdate.setText("");
    }//GEN-LAST:event_cmdDclearActionPerformed

    private void txtDageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDageKeyPressed
        // TODO add your handling code here:
         int c = evt.getKeyChar();
       if((Character.isDigit(c))||(Character.isISOControl(c)))
       {
            txtDage .setEnabled(true);
       }
       else{
      JOptionPane.showMessageDialog(null,"Invalid A Please Enter Another");
      txtDage.setText("");
      txtDage.grabFocus();
       }
       
    }//GEN-LAST:event_txtDageKeyPressed

    private void txtDnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDnameKeyPressed
        // TODO add your handling code here:
                int c = evt.getKeyChar();
       if((Character.isDigit(c)))
       {
          
           JOptionPane.showMessageDialog(null,"Invalid Name Please Enter Another");
           txtDname.setText("");
           txtDname.grabFocus();
       }
       else{
           txtDname .setEnabled(true);
           
       }
    }//GEN-LAST:event_txtDnameKeyPressed

    private void txtDphnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDphnKeyPressed
        // TODO add your handling code here:
             int c = evt.getKeyChar();
       if((Character.isDigit(c))||(Character.isISOControl(c)))
       {
            txtDphn .setEnabled(true);
       }
       else{
      JOptionPane.showMessageDialog(null,"Invalid Number Please Enter Another");
      txtDphn.setText("");
      txtDphn.grabFocus();
       }
    }//GEN-LAST:event_txtDphnKeyPressed

    private void txtDphnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDphnFocusLost
        // TODO add your handling code here:
          String Phn=txtDphn.getText();
        if(Phn.length()!=10)
        {
            txtDphn.setText("");
        }
    }//GEN-LAST:event_txtDphnFocusLost

    private void cmdDdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDdeleteActionPerformed
        // TODO add your handling code here:
              Connection cn;
        Statement st;

        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            cn=DriverManager.getConnection("jdbc:odbc:DATABASE");
            st=cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String str="update Driver set Dname ='"+txtDname.getText()+"',Dphn='"+txtDphn.getText()+"',Demail='"+txtDemail.getText()+"',Daddress='"+txtDaddress.getText()+"',Dage="+txtDage.getText()+",Dlic='"+txtDlic.getText()+"',Ddate='"+txtDdate.getText()+"' where ID="+txtDid.getText();
            System.out.println(str);
            int k=st.executeUpdate(str);
            if(k>0)
            {
                JOptionPane.showMessageDialog(null, "Updated Succsessfully!!!");
            }
        }
        catch(    ClassNotFoundException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,"Plsease Try Again","frmEnquiry",JOptionPane.OK_CANCEL_OPTION);
            cmdDdelete.grabFocus();
        }    
        
    }//GEN-LAST:event_cmdDdeleteActionPerformed

    private void txtDlicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDlicKeyPressed
        // TODO add your handling code here:
                 int c = evt.getKeyChar();
       if((Character.isDigit(c))||(Character.isISOControl(c)))
       {
            txtDlic.setEnabled(true);
       }
       else{
      JOptionPane.showMessageDialog(null,"Invalid Licence Number Please Enter Another");
      txtDlic.setText("");
      txtDlic.grabFocus();
       }
    }//GEN-LAST:event_txtDlicKeyPressed

    private void txtDemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDemailFocusLost
        // TODO add your handling code here:
        String email=txtDemail.getText();
        if(!Pattern.matches("^[a-z0-9 ]+[@]{1}+[gmail]+[.]{1}+[com]+$",email))
                {
                    txtDemail.setText("");
                }
        else{
                
        }
    }//GEN-LAST:event_txtDemailFocusLost

    private void cmdDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDelActionPerformed
        // TODO add your handling code here:
         Connection cn;
        Statement st;

        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            cn=DriverManager.getConnection("jdbc:odbc:DATABASE");
            st=cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String str="delete * from Driver where ID="+txtDid.getText()+"";
            System.out.println(str);
            int k=st.executeUpdate(str);
            if(k>0)
            {
                JOptionPane.showMessageDialog(null, "Delete  Succsessfully!!!");
            }
        }
        catch(    ClassNotFoundException | SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,"Plsease Try Again","frmEnquiry",JOptionPane.OK_CANCEL_OPTION);
        } 
    }//GEN-LAST:event_cmdDelActionPerformed

    private void txtDlicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDlicFocusLost
        // TODO add your handling code here:
          String Phn=txtDlic.getText();
        if(Phn.length()!=10)
        {
            txtDlic.setText("");
        }
    }//GEN-LAST:event_txtDlicFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDcancle;
    private javax.swing.JButton cmdDclear;
    private javax.swing.JButton cmdDdelete;
    private javax.swing.JButton cmdDel;
    private javax.swing.JButton cmdDnew;
    private javax.swing.JButton cmdDprint;
    private javax.swing.JButton cmdDsave;
    private javax.swing.JButton cmdDsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtDaddress;
    private javax.swing.JTextField txtDage;
    private javax.swing.JTextField txtDdate;
    private javax.swing.JTextField txtDemail;
    private javax.swing.JTextField txtDid;
    private javax.swing.JTextField txtDlic;
    private javax.swing.JTextField txtDname;
    private javax.swing.JTextField txtDphn;
    // End of variables declaration//GEN-END:variables
}
